### ISSUE TITLE
Add license?

### ISSUE THREAD

**Issue by fire** [drcd1/GodotSimpleExplosionVFX#2]
There is no license.

**Comment by Calinou** [comment]
Bump :slightly_smiling_face: 

See [Choose a License](https://choosealicense.com/) for more information.

cc @drcd1

**Comment by drcd1** [comment]
Thank you for the reminder :)

I licensed the project under the MIT License (LICENSE.txt), but I'm not sure if this is the most appropriate or if I should use CC-BY to license the data. Alternatively, I'm considering just re-licensing everything under CC0.

**Comment by Calinou** [comment]
@drcd1 Thanks! You could use MIT for code and CC0 for data, that works too.
